defmodule Snappy.Client do
  use Riffed.Client,
  structs: Snappy.Models,
  client_opts: [
    host: "192.168.1.74",
    port: 10000,
    retries: 3,
    framed: true
  ],
  service: :g_f_x_d_service_thrift,
  import: [:getPreferredServer,
           :getAllServersWithPreferredServer,
           :openConnection,
           :execute,
           :executeUpdate,
           :executeQuery,
           :prepareStatement,
           :executePrepared,
           :executePreparedUpdate,
           :executePreparedQuery,
           :executePreparedBatch,
           :prepareAndExecute,
           :beginTransaction,
           :setTransactionAttributes,
           :getTransactionAttributes,
           :commitTransaction,
           :rollbackTransaction,
           :prepareCommitTransaction,
           :getNextResultSet,
           :getBlobChunk,
           :getClobChunk,
           :sendBlobChunk,
           :sendClobChunk,
           :freeLob,
           :scrollCursor,
           :executeCursorUpdate,
           :getServiceMetaData,
           :getSchemaMetaData,
           :getIndexInfo,
           :getUDTs,
           :getBestRowIdentifier,
           # end meta-data API
           :fetchActiveConnections,
           :fetchActiveStatements,
           :cancelStatement,
           :closeResultSet,
           :closeStatement,
           :closeConnection,
           :bulkClose]
end
